<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="3r_manipulator">

    <xacro:include filename="urdf_include.xacro" />

    <link name="world" />


    <joint name="base_joint" type="fixed">
        <parent link="world" />
        <child link="base_link" />
        <axis xyz="0 0 0" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <xacro:property name="base_length" value="0.15" />
    <xacro:property name="base_radius" value="0.2" />
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0  0" />
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}" />
            </geometry>
        </collision>
    </link>

    <joint name="joint1" type="revolute">
        <parent link="base_link" />
        <child link="body_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="0" upper="${pi/2}" velocity="100" effort="100" />
    </joint>

    <xacro:property name="body_length" value="1" />
    <xacro:property name="body_radius" value="0.07" />
    <link name="body_link">
        <visual>
            <origin xyz="0 0 ${body_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${body_length}" radius="${body_radius}" />
            </geometry>
            <material name="blue" />

        </visual>
        <collision>
            <origin xyz="0 0 ${body_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${body_length}" radius="${body_radius}" />
            </geometry>
        </collision>
    </link>
    <joint name="joint2" type="revolute">
        <parent link="body_link" />
        <child link="shoulder_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="0 0 ${body_length}" rpy="0 0 0" />
        <limit lower="-${pi/4}" upper="${pi/4}" velocity="100" effort="100" />
    </joint>
    <xacro:property name="shoulder_length" value="0.15" />
    <xacro:property name="shoulder_radius" value="0.07" />
    <link name="shoulder_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0  0" />
            <geometry>
                <cylinder length="${shoulder_length}" radius="${shoulder_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0  0" />
            <geometry>
                <cylinder length="${shoulder_length}" radius="${shoulder_radius}" />
            </geometry>
        </collision>
    </link>

    <joint name="joint3" type="fixed">
        <parent link="shoulder_link" />
        <child link="arm_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <xacro:property name="arm_length" value="1" />
    <xacro:property name="arm_radius" value="0.07" />
    <link name="arm_link">
        <visual>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
        </collision>
    </link>
    <joint name="joint4" type="revolute">
        <parent link="arm_link" />
        <child link="elbow_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="${arm_length} 0 0" rpy="0 0 0" />
        <limit lower="-${pi/3}" upper="${pi/3}" velocity="100" effort="100" />

    </joint>
    <xacro:property name="elbow_length" value="0.15" />
    <xacro:property name="elbow_radius" value="0.07" />
    <link name="elbow_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0  0" />
            <geometry>
                <cylinder length="${elbow_length}" radius="${elbow_radius}" />
            </geometry>
            <material name="orange" />

        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0  0" />
            <geometry>
                <cylinder length="${elbow_length}" radius="${elbow_radius}" />
            </geometry>
        </collision>
    </link>

    <joint name="joint5" type="fixed">
        <parent link="elbow_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
    </joint>

    <xacro:property name="forearm_length" value="0.5" />
    <xacro:property name="forearm_radius" value="0.07" />
    <link name="forearm_link">
        <visual>
            <origin xyz="${forearm_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="${forearm_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}" />
            </geometry>
        </collision>
    </link>
</robot>